# Generated by Django 4.0.3 on 2022-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=125)),
                ('roll1', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('name2', models.CharField(max_length=125)),
                ('roll2', models.CharField(max_length=12)),
                ('room', models.CharField(max_length=10)),
                ('entrytime', models.TimeField()),
            ],
        ),
    ]
